#!/bin/bash

IPADDR=`hostname -I`

BeginNum=`echo "$IPADDR"` | cut -c 1
lastNumIP=${IPADDR##$BeginNum*.}
TakeoutIP=${IPADDR%$lastNumIP}


num=1
until [ $num -gt 255 ]
do
  ChangeIP="$TakeoutIP$num"
  if ping -c 1 -W 1 "$ChangeIP" >/dev/null 2>&1; then
    echo $ChangeIP : alive
    host=`host $ChangeIP | cut -d' ' -f5`
    echo "host : $host"
    MacAddressFile=`grep $ChangeIP /proc/net/arp`
    MACaddress=`echo $MacAddressFile | cut -d' ' -f4`
    echo HW : $MACaddress
    if nc -z -w 1 $ChangeIP 22; then
      echo "Port 22 : Successful!"
    else
      echo "Port 22 : Not available"
    fi
    if nc -z -w 1 $ChangeIP 80; then
      echo "Port 80 : Successful!"
    else
      echo "Port 80 : Not available"
  echo " "
    fi
  fi
((num++))
done
